language: csharp

mono: none
dotnet: 2.1.403

script:
  - dotnet test ./test/Camunda.Worker.Tests/Camunda.Worker.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

notifications:
  email: false
